/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'description' : string,
  'timestamp' : Time,
  'eventType' : string,
}
export interface Alert {
  'id' : bigint,
  'childId' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface ChildProfile {
  'id' : bigint,
  'age' : bigint,
  'creationTimestamp' : Time,
  'name' : string,
  'avatarColor' : string,
  'deviceName' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<[bigint, string], undefined>,
  'createChildProfile' : ActorMethod<[string, bigint, string, string], bigint>,
  'deleteChildProfile' : ActorMethod<[bigint], undefined>,
  'getAlertsForChild' : ActorMethod<[bigint], Array<Alert>>,
  'getAllChildren' : ActorMethod<[], Array<ChildProfile>>,
  'getBlockedCategories' : ActorMethod<[bigint], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getDailyScreenTimeLimit' : ActorMethod<[bigint], [] | [bigint]>,
  'getDailyUsage' : ActorMethod<[bigint, string], bigint>,
  'getLastNActivities' : ActorMethod<[bigint, bigint], Array<ActivityEvent>>,
  'getSafeBrowsingStatus' : ActorMethod<[bigint], boolean>,
  'getUnreadAlerts' : ActorMethod<[], Array<Alert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasExceededDailyLimit' : ActorMethod<[bigint, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCategoryBlocked' : ActorMethod<[bigint, string], boolean>,
  'logActivity' : ActorMethod<[bigint, string, string], undefined>,
  'markAlertAsRead' : ActorMethod<[bigint], undefined>,
  'markAllAlertsAsRead' : ActorMethod<[], undefined>,
  'recordScreenTimeUsage' : ActorMethod<[bigint, string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCategoryControl' : ActorMethod<[bigint, string, boolean], undefined>,
  'setDailyScreenTimeLimit' : ActorMethod<[bigint, bigint], undefined>,
  'setSafeBrowsingStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateChildProfile' : ActorMethod<
    [bigint, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];