/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'childId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ChildProfile = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'creationTimestamp' : Time,
  'name' : IDL.Text,
  'avatarColor' : IDL.Text,
  'deviceName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ActivityEvent = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createChildProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteChildProfile' : IDL.Func([IDL.Nat], [], []),
  'getAlertsForChild' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'getAllChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
  'getBlockedCategories' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDailyScreenTimeLimit' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getDailyUsage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], ['query']),
  'getLastNActivities' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getSafeBrowsingStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getUnreadAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasExceededDailyLimit' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCategoryBlocked' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'markAlertAsRead' : IDL.Func([IDL.Nat], [], []),
  'markAllAlertsAsRead' : IDL.Func([], [], []),
  'recordScreenTimeUsage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCategoryControl' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'setDailyScreenTimeLimit' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setSafeBrowsingStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateChildProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'childId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ChildProfile = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'creationTimestamp' : Time,
    'name' : IDL.Text,
    'avatarColor' : IDL.Text,
    'deviceName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ActivityEvent = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createChildProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteChildProfile' : IDL.Func([IDL.Nat], [], []),
    'getAlertsForChild' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
    'getAllChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
    'getBlockedCategories' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDailyScreenTimeLimit' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getDailyUsage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], ['query']),
    'getLastNActivities' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getSafeBrowsingStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getUnreadAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasExceededDailyLimit' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCategoryBlocked' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'markAlertAsRead' : IDL.Func([IDL.Nat], [], []),
    'markAllAlertsAsRead' : IDL.Func([], [], []),
    'recordScreenTimeUsage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCategoryControl' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'setDailyScreenTimeLimit' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setSafeBrowsingStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateChildProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };